-- V1.0.1 基础数据表
CREATE TABLE base_material (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_code       VARCHAR(50)  NOT NULL,
    material_name       VARCHAR(200) NOT NULL,
    category_code       VARCHAR(50)  NOT NULL,
    specification       VARCHAR(200),
    model               VARCHAR(100),
    unit_code           VARCHAR(20)  NOT NULL,
    aux_unit_code       VARCHAR(20),
    convert_rate        DECIMAL(18,4),
    material_type       VARCHAR(20)  NOT NULL,
    barcode_type        VARCHAR(20)  NOT NULL DEFAULT 'CODE128',
    barcode_rule        VARCHAR(50),
    batch_managed       INT          NOT NULL DEFAULT 1,
    serial_managed      INT          NOT NULL DEFAULT 0,
    shelf_life_managed  INT          NOT NULL DEFAULT 0,
    shelf_life_days     INT,
    warning_days        INT,
    safety_stock        DECIMAL(18,4) DEFAULT 0,
    max_stock           DECIMAL(18,4),
    abc_class           VARCHAR(1),
    weight              DECIMAL(18,4),
    volume              DECIMAL(18,4),
    default_wh          VARCHAR(50),
    default_loc         VARCHAR(50),
    status              INT          NOT NULL DEFAULT 1,
    remark              VARCHAR(500),
    create_by           VARCHAR(50)  NOT NULL DEFAULT 'system',
    create_time         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           VARCHAR(50),
    update_time         TIMESTAMP,
    deleted             INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_material_code UNIQUE (material_code)
);

CREATE TABLE base_material_category (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(50)  NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    parent_code   VARCHAR(50),
    sort_order    INT DEFAULT 0,
    status        INT NOT NULL DEFAULT 1,
    deleted       INT NOT NULL DEFAULT 0
);

CREATE TABLE base_supplier (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code   VARCHAR(50)  NOT NULL,
    supplier_name   VARCHAR(200) NOT NULL,
    short_name      VARCHAR(50),
    contact_person  VARCHAR(50),
    contact_phone   VARCHAR(20),
    email           VARCHAR(100),
    address         VARCHAR(200),
    status          INT NOT NULL DEFAULT 1,
    remark          VARCHAR(500),
    create_by       VARCHAR(50) NOT NULL DEFAULT 'system',
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_supplier_code UNIQUE (supplier_code)
);

CREATE TABLE base_customer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code   VARCHAR(50)  NOT NULL,
    customer_name   VARCHAR(200) NOT NULL,
    short_name      VARCHAR(50),
    contact_person  VARCHAR(50),
    contact_phone   VARCHAR(20),
    email           VARCHAR(100),
    address         VARCHAR(200),
    status          INT NOT NULL DEFAULT 1,
    create_by       VARCHAR(50) NOT NULL DEFAULT 'system',
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_customer_code UNIQUE (customer_code)
);

CREATE TABLE base_warehouse (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code  VARCHAR(50)  NOT NULL,
    warehouse_name  VARCHAR(100) NOT NULL,
    warehouse_type  VARCHAR(20)  NOT NULL,
    factory_code    VARCHAR(50),
    address         VARCHAR(200),
    manager_id      VARCHAR(50),
    phone           VARCHAR(20),
    status          INT NOT NULL DEFAULT 1,
    remark          VARCHAR(500),
    create_by       VARCHAR(50) NOT NULL DEFAULT 'system',
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_warehouse_code UNIQUE (warehouse_code)
);

CREATE TABLE base_warehouse_zone (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_code     VARCHAR(50) NOT NULL,
    zone_name     VARCHAR(100) NOT NULL,
    warehouse_code VARCHAR(50) NOT NULL,
    status        INT NOT NULL DEFAULT 1,
    deleted       INT NOT NULL DEFAULT 0
);

CREATE TABLE base_location (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code   VARCHAR(50)  NOT NULL,
    location_name   VARCHAR(100) NOT NULL,
    warehouse_code  VARCHAR(50)  NOT NULL,
    zone_code       VARCHAR(50)  NOT NULL,
    location_type   VARCHAR(20)  NOT NULL,
    row_no          INT,
    col_no          INT,
    layer_no        INT,
    max_capacity    DECIMAL(18,4),
    capacity_unit   VARCHAR(20),
    mixed_material  INT NOT NULL DEFAULT 0,
    mixed_batch     INT NOT NULL DEFAULT 1,
    status          INT NOT NULL DEFAULT 1,
    remark          VARCHAR(500),
    create_by       VARCHAR(50) NOT NULL DEFAULT 'system',
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_location_code UNIQUE (location_code)
);

CREATE TABLE base_unit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_code   VARCHAR(20) NOT NULL,
    unit_name   VARCHAR(50) NOT NULL,
    status      INT NOT NULL DEFAULT 1,
    deleted     INT NOT NULL DEFAULT 0
);
