-- 阶段C（安全/埋点/告警）：密码过期时间 + 事件埋点表 + 告警表

-- C2.4 密码 90 天过期：记录最近一次密码修改时间
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS pwd_updated_at TIMESTAMP;
UPDATE sys_user SET pwd_updated_at = CURRENT_TIMESTAMP WHERE pwd_updated_at IS NULL;

-- C3.1 数据埋点事件表
CREATE TABLE IF NOT EXISTS mes_event_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name      VARCHAR(50)  NOT NULL,
    biz_type        VARCHAR(30),
    biz_no          VARCHAR(50),
    operator_id     VARCHAR(50),
    operator_name   VARCHAR(100),
    properties      CLOB,
    event_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_mes_event_log_name_time ON mes_event_log (event_name, event_time);
CREATE INDEX IF NOT EXISTS ix_mes_event_log_biz_no ON mes_event_log (biz_no);

-- C4.1 告警表（队列满 / SLA / 长期未同步）
CREATE TABLE IF NOT EXISTS sys_alert (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type      VARCHAR(30)  NOT NULL,
    level           VARCHAR(10)  NOT NULL DEFAULT 'WARN',
    title           VARCHAR(200) NOT NULL,
    content         VARCHAR(1000),
    biz_no          VARCHAR(50),
    status          VARCHAR(10)  NOT NULL DEFAULT 'OPEN',
    alert_count     INT NOT NULL DEFAULT 1,
    first_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ack_by          VARCHAR(50),
    ack_time        TIMESTAMP,
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_sys_alert_status ON sys_alert (status, alert_type);
