CREATE TABLE label_print_job (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    job_id              VARCHAR(32) NOT NULL,
    source_type         VARCHAR(30) NOT NULL DEFAULT 'KINGDEE',
    source_bill_no      VARCHAR(64),
    material_code       VARCHAR(64) NOT NULL,
    material_name       VARCHAR(200),
    specification       VARCHAR(200),
    batch_no            VARCHAR(64),
    quantity            DECIMAL(18,4),
    unit_code           VARCHAR(20),
    barcode_content     VARCHAR(200) NOT NULL,
    barcode_type        VARCHAR(20) NOT NULL DEFAULT 'QR',
    label_width_mm      DECIMAL(8,2) DEFAULT 100,
    label_height_mm     DECIMAL(8,2) DEFAULT 60,
    copies              INT NOT NULL DEFAULT 1,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    operator_id         VARCHAR(50),
    operator_name       VARCHAR(50),
    request_payload     CLOB,
    error_message       VARCHAR(500),
    create_time         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opened_time         TIMESTAMP,
    printed_time        TIMESTAMP,
    CONSTRAINT uk_label_print_job_id UNIQUE (job_id)
);
