-- V1.0.2 业务核心表
CREATE TABLE inbound_order (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no            VARCHAR(30) NOT NULL,
    order_type          VARCHAR(20) NOT NULL,
    warehouse_code      VARCHAR(50) NOT NULL,
    supplier_code       VARCHAR(50),
    production_order_no VARCHAR(30),
    source_order_no     VARCHAR(30),
    plan_date           DATE NOT NULL,
    actual_date         TIMESTAMP,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    creator_id          VARCHAR(50) NOT NULL,
    creator_name        VARCHAR(50) NOT NULL,
    auditor_id          VARCHAR(50),
    auditor_name        VARCHAR(50),
    audit_time          TIMESTAMP,
    attachments         CLOB,
    remark              VARCHAR(500),
    create_time         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP,
    deleted             INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_inbound_order_no UNIQUE (order_no)
);

CREATE TABLE inbound_order_detail (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no        VARCHAR(30) NOT NULL,
    line_no         INT NOT NULL,
    material_code   VARCHAR(50) NOT NULL,
    material_name   VARCHAR(200),
    specification   VARCHAR(200),
    unit_code       VARCHAR(20) NOT NULL,
    order_qty       DECIMAL(18,4) NOT NULL,
    received_qty    DECIMAL(18,4) DEFAULT 0,
    batch_no        VARCHAR(50),
    production_date DATE,
    expire_date     DATE,
    target_location VARCHAR(50),
    qc_status       VARCHAR(20),
    line_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    remark          VARCHAR(500)
);

CREATE TABLE outbound_order (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no            VARCHAR(30) NOT NULL,
    order_type          VARCHAR(20) NOT NULL,
    warehouse_code      VARCHAR(50) NOT NULL,
    production_order_no VARCHAR(30),
    customer_code       VARCHAR(50),
    plan_date           DATE NOT NULL,
    actual_date         TIMESTAMP,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    creator_id          VARCHAR(50) NOT NULL,
    creator_name        VARCHAR(50) NOT NULL,
    auditor_id          VARCHAR(50),
    auditor_name        VARCHAR(50),
    audit_time          TIMESTAMP,
    remark              VARCHAR(500),
    create_time         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP,
    deleted             INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_outbound_order_no UNIQUE (order_no)
);

CREATE TABLE outbound_order_detail (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no        VARCHAR(30) NOT NULL,
    line_no         INT NOT NULL,
    material_code   VARCHAR(50) NOT NULL,
    material_name   VARCHAR(200),
    specification   VARCHAR(200),
    unit_code       VARCHAR(20) NOT NULL,
    demand_qty      DECIMAL(18,4) NOT NULL,
    issued_qty      DECIMAL(18,4) DEFAULT 0,
    batch_no        VARCHAR(50),
    source_location VARCHAR(50),
    line_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    remark          VARCHAR(500)
);

CREATE TABLE inventory (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code  VARCHAR(50) NOT NULL,
    location_code   VARCHAR(50) NOT NULL,
    material_code   VARCHAR(50) NOT NULL,
    batch_no        VARCHAR(50) DEFAULT '',
    stock_qty       DECIMAL(18,4) NOT NULL DEFAULT 0,
    available_qty   DECIMAL(18,4) NOT NULL DEFAULT 0,
    frozen_qty      DECIMAL(18,4) NOT NULL DEFAULT 0,
    in_transit_qty  DECIMAL(18,4) NOT NULL DEFAULT 0,
    inbound_date    TIMESTAMP,
    production_date DATE,
    expire_date     DATE,
    stock_status    VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    create_time     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP,
    CONSTRAINT uk_inventory UNIQUE (warehouse_code, location_code, material_code, batch_no)
);

CREATE TABLE inventory_transaction (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_no      VARCHAR(30) NOT NULL,
    transaction_type    VARCHAR(20) NOT NULL,
    warehouse_code      VARCHAR(50) NOT NULL,
    location_code       VARCHAR(50) NOT NULL,
    material_code       VARCHAR(50) NOT NULL,
    batch_no            VARCHAR(50) DEFAULT '',
    transaction_qty     DECIMAL(18,4) NOT NULL,
    before_qty          DECIMAL(18,4) NOT NULL,
    after_qty           DECIMAL(18,4) NOT NULL,
    source_order_type   VARCHAR(20),
    source_order_no     VARCHAR(30),
    source_order_line   INT,
    operator_id         VARCHAR(50) NOT NULL,
    operator_name       VARCHAR(50) NOT NULL,
    device_no           VARCHAR(50),
    operation_time      TIMESTAMP NOT NULL,
    remark              VARCHAR(500),
    create_time         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_txn_no UNIQUE (transaction_no)
);

CREATE TABLE transfer_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no     VARCHAR(30) NOT NULL,
    transfer_type   VARCHAR(20) NOT NULL,
    source_warehouse VARCHAR(50) NOT NULL,
    source_location VARCHAR(50) NOT NULL,
    target_warehouse VARCHAR(50) NOT NULL,
    target_location VARCHAR(50) NOT NULL,
    material_code   VARCHAR(50) NOT NULL,
    batch_no        VARCHAR(50),
    transfer_qty    DECIMAL(18,4) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    operator_id     VARCHAR(50),
    operation_time  TIMESTAMP,
    CONSTRAINT uk_transfer_no UNIQUE (transfer_no)
);

CREATE TABLE pda_task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     VARCHAR(30) NOT NULL,
    task_type   VARCHAR(20) NOT NULL,
    assignee_id VARCHAR(50),
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    priority    VARCHAR(20) DEFAULT 'NORMAL',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE message (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    message_type VARCHAR(20) NOT NULL,
    title        VARCHAR(200) NOT NULL,
    content      VARCHAR(1000),
    is_read      INT NOT NULL DEFAULT 0,
    create_time  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE barcode_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code    VARCHAR(50) NOT NULL,
    rule_name    VARCHAR(100) NOT NULL,
    applies_to   VARCHAR(20),
    barcode_type VARCHAR(20),
    segments_json CLOB,
    status       INT NOT NULL DEFAULT 1,
    CONSTRAINT uk_barcode_rule_code UNIQUE (rule_code)
);
