-- 轻MES：不良单 / 返工工单回传 ERP 的出站队列
-- action: CREATE（不良单创建时新增金蝶单据）/ SUBMIT（返工完成时提交并审核）
-- biz_type: DEFECT（不良单）/ REWORK（返工工单）

CREATE TABLE mes_erp_outbox (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biz_type            VARCHAR(16)  NOT NULL,
    biz_no              VARCHAR(64)  NOT NULL,
    action              VARCHAR(16)  NOT NULL,
    sync_status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    retry_count         INT          NOT NULL DEFAULT 0,
    next_retry_time     TIMESTAMP,
    erp_bill_no         VARCHAR(64),
    erp_bill_id         BIGINT,
    fail_reason         VARCHAR(500),
    last_sync_time      TIMESTAMP,
    create_by           VARCHAR(50)  NOT NULL DEFAULT 'system',
    create_time         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           VARCHAR(50),
    update_time         TIMESTAMP,
    deleted             INT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_mes_erp_outbox UNIQUE (biz_type, biz_no, action)
);

CREATE INDEX ix_mes_erp_outbox_status ON mes_erp_outbox (sync_status, next_retry_time);
